---
language: node_js
node_js:
  - "stable"
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
addons:
  code_climate:
    repo_token: 2329e18b632d5caaf918bab043ec028442ee02579a26b76bcf55be7f1a952596
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < test/unit/coverage/lcov.info
