---
language: node_js
node_js:
  - "stable"
sudo: required
cache:
  directories:
    - node_modules
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - npm test
addons:
  code_climate:
    repo_token: e82f41a6abbb8e09b5d5e7af1ce0a271115ce6681d390ed7107e88c2458ea872
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < test/unit/coverage/lcov.info
